name: Tests
on: push

jobs:
  # PHP Tests
  # ---------------------------------------------------------------
  php:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: |
            composer global require squizlabs/php_codesniffer wp-coding-standards/wpcs
            phpcs --config-set installed_paths /home/runner/.composer/vendor/wp-coding-standards/wpcs

      - name: PHPCS
        run: |
            phpcs --config-set show_warnings 0
            phpcs

      # - name: PHPUnit
      #   run: php -d memory_limit=-1 ./vendor/bin/phpunit

  # Javascript Tests
  # ---------------------------------------------------------------
  js:
    name: JS Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Eslint
        run: yarn lint-js
